on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          
      - name: Deploy RotaryUtils
        run: |
          ssh -i id_rsa ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} <<'ENDSSH'
            echo "Connected"
            cd /opt/apps/myrotary-rust-utils/
            sudo git stash 
            sudo git pull #public repo so i can do this directly without PAT token
            sudo cp /opt/apps/productionfiles/utils/.env /opt/apps/myrotary-rust-utils/cli
            sudo cp /opt/apps/productionfiles/utils/.server.env /opt/apps/myrotary-rust-utils/server/.env
            cd cli
            #  Build the project with elevated permissions and explicit environment variables
            sudo RUSTUP_HOME=$HOME/.rustup CARGO_HOME=$HOME/.cargo ~/.cargo/bin/cargo build --release
            sudo ln -sf /opt/apps/myrotary-rust-utils/cli/target/release/myrotary-rust-utils /usr/local/bin/myrotary-rust-utils # force create symbolic link to binary
            cd /opt/apps/myrotary-rust-utils/server
            sudo RUSTUP_HOME=$HOME/.rustup CARGO_HOME=$HOME/.cargo ~/.cargo/bin/cargo build --release
          ENDSSH
